# 本地开发环境配置模板
# 复制此文件为application-local.yml并修改为你自己的配置

server:
  port: 8080  # 本地开发端口，可根据需要修改

# DeepSeek API配置 - 替换为你自己的密钥
deepseek:
  api:
    url: https://api.deepseek.com/v1/chat/completions
    key: YOUR_PERSONAL_DEEPSEEK_API_KEY  # 替换为你的实际密钥

# 火山引擎API配置 - 替换为你自己的密钥
volcengine:
  api:
    key: YOUR_PERSONAL_VOLCENGINE_API_KEY  # 替换为你的实际密钥
    timeout: 60
    model: doubao-lite-128k-240828
    prompt: ${analysis.prompt}  # 引用主配置中的提示词

# 本地环境可能使用模拟数据
ai:
  use-mock-on-failure: true  # API调用失败时使用模拟数据
  # 如果没有API密钥，可以使用模拟数据
  # provider: mock  # 取消注释此行以使用模拟数据

# 本地环境日志配置
logging:
  level:
    root: INFO
    com.bazi: DEBUG
    org.springframework.web: DEBUG 